name: my_pocket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  animated_toggle_switch: ^0.8.4
  bloc: ^8.1.4
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  go_router: ^14.6.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF_Pro_display/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF_Pro_display/SF-Pro-Display-SemiBold.otf
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF_Pro_text/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF_Pro_text/SF-Pro-Text-SemiBold.otf
        - asset: assets/fonts/SF_Pro_text/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF_Pro_text/SF-Pro-Text-Regular.otf
