// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByC9foRUJFLzhyvx__JWgtQ1eEAkS7wV0',
    appId: '1:531186674322:web:afcfcc507236e255d6d44b',
    messagingSenderId: '531186674322',
    projectId: 'my-pocket-2f09e',
    authDomain: 'my-pocket-2f09e.firebaseapp.com',
    storageBucket: 'my-pocket-2f09e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiQwBkcuTEY9GIUBsnzfSoGepI0HMPec',
    appId: '1:531186674322:android:c1bf9a00119da2b4d6d44b',
    messagingSenderId: '531186674322',
    projectId: 'my-pocket-2f09e',
    storageBucket: 'my-pocket-2f09e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYIG4FD27tAoNxZDa46xm06sMQOPP1GTg',
    appId: '1:531186674322:ios:91c46ae35ed2353ad6d44b',
    messagingSenderId: '531186674322',
    projectId: 'my-pocket-2f09e',
    storageBucket: 'my-pocket-2f09e.firebasestorage.app',
    iosBundleId: 'com.example.myPocket',
  );
}
